# Datenstrom Yellow extension settings

Extension: Serve
Version: 1.0.1
Description: Built-in web server.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-serve/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-serve
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:44
Status: maintained
system/workers/serve.php: serve.php, create, update
